In [1]:
import numpy as np
x= np.array([3,5,2,7,8,4,5])
type(x)

def remove_duplicate(x):
    new_arr=[]
    for i in x:
        if i not in new_arr:
            new_arr.append(i)
    return new_arr

result= remove_duplicate(x)
print(result)

[3, 5, 2, 7, 8, 4]


In [7]:
import numpy as np
x= np.array([3,5,2,7,8,4,5])
result=list(set(x))
result

[2, 3, 4, 5, 7, 8]

In [21]:
import numpy as np
x= np.array([3,5,2,7,8,4,5])
result=set(x)
result

array({2, 3, 4, 5, 7, 8}, dtype=object)

In [23]:
import numpy as np
x= np.array([3,5,2,7,8,4,5])
result=np.array(x)
result

array([3, 5, 2, 7, 8, 4, 5])

In [29]:
import numpy as np
x= np.array([3,5,2,7,8,4,5])
a=set(x)
b=np.array(list(a))
b

array([2, 3, 4, 5, 7, 8])

In [31]:
import numpy as np
x= np.array([3,5,2,7,8,4,5])
print(type(x))

def remove_duplicate(x):
    unique_element=list(set(x))
    return np.array(unique_element)

result=remove_duplicate(x)
result

<class 'numpy.ndarray'>


array([2, 3, 4, 5, 7, 8])